config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '/user', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  namespace :users, path: '/user' do
    get '/testimonial', to: 'testimonials#edit'
    patch '/testimonial', to: 'testimonials#update'
    delete '/testimonial', to: 'testimonials#destroy'
  end

  namespace :admin do
    root 'admins#index'

    resources :emails, only: [:index, :show, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :testimonials do
      collection do
        delete 'destroy_multiple'
      end

      resource :highlight, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :reports, only: [:index, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get '/customers', to: 'users#index'
    delete '/customers/delete/:id', to: 'users#destroy', as: 'delete_customer'
    get '/profile/edit', to: 'admins#edit'
    patch '/profile/edit', to: 'admins#update'
    post '/send_testimonial_link/:id', to: 'users#send_testimonial_link'
    get '/password/edit', to: 'passwords#edit'
    patch '/password/edit', to: 'passwords#update'
    get '/search', to: 'searches#index'
  end

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/privacy-policy', to: 'pages#privacy_policy'
  get '/contact', to: 'users/emails#new'
  post '/contact', to: 'users/emails#create'
  get '/testimonials', to: 'users/testimonials#index'
  get '/testimonial/:token', to: 'users/testimonials#new', as: 'new_user_testimonial'
  post '/testimonial/:token', to: 'users/testimonials#create'
  get '/photos', to: 'users/photos#index'
  get 'expired_token', to: 'users/testimonials#expired_token', as: 'expired_token'
  get 'api/density_altitude', to: 'api/density_altitude#create'
end

app/views/shared/_flash_notice.html.haml
- flash.each do |k, v|
  - unless k == 'timedout'
    %div{class: flash_class(k)}
      = v
      = button_tag(type: 'button', class: 'close', data: {dismiss: 'alert'}, aria: {label: 'Close'}) do
        = content_tag :span, aria: {hidden: 'true'} do
          &times;

app/views/shared/_footer.html.erb
<footer class="flex-rw pt-3">
  <section class="footer-social-section flex-rw">
      <span class="footer-social-overlap footer-social-connect">
      CONNECT <span class="footer-social-small">with</span> US
      </span>
      <span class="footer-social-overlap footer-social-icons-wrapper">
        <%= link_to "tel:7192513973", class: "generic-anchor", :title => '719-251-3973', :data => { :toggle => 'tooltip', :placement => 'top' } do %>
          <%= fa_icon 'phone' %>
        <% end %>
        <%= link_to 'https://www.facebook.com', class: "generic-anchor", target: "_blank" do %>
          <%= fa_icon 'facebook-square' %>
        <% end %>
        <%= link_to contact_path, class: "generic-anchor" do %>
          <%= fa_icon 'envelope' %>
        <% end %>
        <%= link_to 'https://www.instagram.com/kaseykoch55/', class: "generic-anchor", target: "_blank" do %>
          <%= fa_icon 'instagram' %>
        <% end %>
      </span>
  </section>
  <section class="footer-bottom-section flex-rw">
    <div class="footer-bottom-wrapper">
      <i class="fa fa-copyright" role="copyright"></i>
      2019 FrankenKopter in
      <address class="footer-address" role="company address">Big Fork, MT</address>
      <span class="footer-bottom-rights"> - All Rights Reserved - </span>
    </div>
    <div class="footer-bottom-wrapper">
      <%= link_to 'Privacy Policy', privacy_policy_path, class: 'generic-anchor' %>
    </div>
  </section>
</footer>

app/views/shared/_nav.html.erb
<nav id="nav" class="navbar navbar-expand-lg navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
      <% if active['home'] %>
        <li class="nav-item active">
          <%= link_to root_path, class: 'nav-link' do %>
            Home
            <span class="sr-only">(current)</span>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if active['about'] %>
        <li class="nav-item active">
          <%= link_to about_path, class: 'nav-link' do %>
            About
            <span class="sr-only">(current)<span>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if active['contact'] %>
        <li class="nav-item active">
          <%= link_to contact_path, class: 'nav-link' do %>
            Contact
            <span class="sr-only">(current)</span>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if active['photos'] %>
        <li class="nav-item active">
          <%= link_to photos_path, class: 'nav-link' do %>
            Photos
            <span class="sr-only">(current)</span>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Photos', photos_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if active['testimonials'] %>
        <li class="nav-item active">
          <%= link_to testimonials_path, class: 'nav-link' do %>
            Testimonials
            <span class="sr-only">(current)</span>
            <% end %>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Testimonials', testimonials_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
        <% if active['dashboard'] %>
          <li class="nav-item active">
            <%= link_to admin_root_path, class: 'nav-link' do %>
              Dashboard
              <span class="sr-only">(current)</span>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Dashboard', admin_root_path, class: 'nav-link' %>
          </li>
        <% end %>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
        <%= render partial: 'shared/search_dropdown', locals: { active: active } %>
      <% end %>
      <% if user_signed_in? %>
        <%= render partial: 'shared/signed_in_dropdown', locals: { active: active } %>
      <% else %>
        <% render partial: 'shared/signed_out_dropdown', locals: { active: active } %>
      <% end %>
    </ul>
  </div>
  <div class="navbar-nav">
    <% if user_signed_in? %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, id: "sign-out-button", class: 'btn btn-outline-primary' %>
    <% end %>
  </div>
</nav>

app/views/shared/_pagination.html.erb
<nav aria-label="page navigation">
  <ul class="pagination">
    <% if @current_page == 1 %>
      <li class="page-item disabled">
        <%= link_to admin_emails_path(current_user, :page => @current_page - 1, :order => @order), class: "page-link", aria: {label: "Previous"} do %>
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        <% end %>
      </li>
    <% else %>
      <li class="page-item">
        <%= link_to admin_emails_path(current_user, :page => @current_page - 1, :order => @order), class: "page-link", aria: {label: "Previous"} do %>
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        <% end %>
      </li>
    <% end %>
    <% (@records_count / 10.0).ceil.times do |n| %>
      <% if @current_page == n + 1 %>
        <li class="page-item active" %>
          <%= link_to n + 1, admin_emails_path(current_user, :page => n + 1, :order => @order), class: "page-link" %>
      <% else %>
        <li class="page-item" %>
          <%= link_to n + 1, admin_emails_path(current_user, :page => n + 1, :order => @order), class: "page-link" %>
        </li>
      <% end %>
    <% end %>
    <% if @current_page < (@records_count / 10.0).ceil %>
      <li class="page-item">
        <%= link_to admin_emails_path(current_user, :page => @current_page + 1, :order => @order), class: "page-link", aria: {label: "Next"} do %>
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        <% end %>
      </li>
    <% else %>
      <li class="page-item disabled">
        <%= link_to admin_emails_path(current_user, :page => @current_page + 1, :order => @order), class: "page-link", aria: {label: "Next"} do %>
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_search_dropdown.html.erb
<% if active['search'] %>
  <li id="search-dropdown" class="nav-item dropdown active">
    <span class="sr-only">(current)</span>
    <%= link_to nil, class: 'nav-link dropdown-toggle', id: 'searchBarDropdown', role: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'} do %>
      Search
    <% end %>
    <ul class="dropdown-menu" aria-labelledby="searchBarDropdown">
      <li>
        <form id="search-form-2" class="dropdown-item form-inline">
          <input class="form-control mr-1" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <%= fa_icon 'search' %>
          </button>
        </form>
      </li>
    </ul>
  </li>
<% else %>
<li id="search-dropdown" class="nav-item dropdown">
  <%= link_to nil, class: 'nav-link dropdown-toggle', id: 'searchBarDropdown', role: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'} do %>
    Search
  <% end %>
    <ul class="dropdown-menu" aria-labelledby="searchBarDropdown">
      <li>
        <form id="search-form-2" class="dropdown-item form-inline">
          <input class="form-control w-75 d-block mx-auto mb-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success d-block w-75 mx-auto" type="submit">
            <%= fa_icon 'search' %>
          </button>
        </form>
      </li>
    </ul>
  </li>
<% end %>

app/views/shared/_signed_in_dropdown.html.haml
-if active['accounts']
  %li.nav-item.dropdown.active
    %span.sr-only (current)
    =link_to nil, class: 'nav-link dropdown-toggle', id: 'navbarDropdown', role: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'} do
      Account
    %ul.dropdown-menu{ aria: {labelledby: 'navbarDropdown'} }
      -unless current_user.admin?
        %li
          =link_to 'My Account',  edit_user_registration_path, class: 'dropdown-item'
      %li
        -if current_user.admin?
          =link_to 'Edit My Account', admin_profile_edit_path, class: 'dropdown-item'
      %li.dropdown-divider
      %li
        =link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
-else
  %li.nav-item.dropdown
    %span.sr-only (current)
    =link_to nil, class: 'nav-link dropdown-toggle', id: 'navbarDropdown', role: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'} do
      Account
    %ul.dropdown-menu{ aria: {labelledby: 'navbarDropdown'}}
      -unless current_user.admin?
        %li
          =link_to 'My Account',  edit_user_registration_path, class: 'dropdown-item'
      %li
        -if current_user.admin?
          =link_to 'Edit My Account', admin_profile_edit_path, class: 'dropdown-item'
      %li.dropdown-divider
      %li
        =link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'

app/views/shared/_signed_out_dropdown.html.haml
-if active['accounts']
  %li.nav-item.dropdown.active
    %span.sr-only (current)
    =link_to nil, class: 'nav-link dropdown-toggle', id: 'navbarDropdown', role: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'} do
      Account
    %ul.dropdown-menu{ aria: {labelledby: 'navbarDropdown'}}
      %li
        =link_to 'Create An Account', new_user_registration_path, class: 'dropdown-item'
      %li.dropdown-divider
      %li
        =link_to 'Sign In', new_user_session_path(current_user), class: 'dropdown-item'
-else
  %li.nav-item.dropdown
    =link_to nil, class: 'nav-link dropdown-toggle', id: 'navbarDropdown', role: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'} do
      Account
    %ul.dropdown-menu{ aria: {labelledby: 'navbarDropdown'}}
      %li
        =link_to 'Create An Account', new_user_registration_path, class: 'dropdown-item'
      %li.dropdown-divider
      %li
        =link_to 'Sign In', new_user_session_path(current_user), class: 'dropdown-item'