config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '/user', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  namespace :users, path: '/user' do
    get '/testimonial', to: 'testimonials#edit'
    patch '/testimonial', to: 'testimonials#update'
    delete '/testimonial', to: 'testimonials#destroy'
  end

  namespace :admin do
    root 'admins#index'

    resources :emails, only: [:index, :show, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :testimonials do
      collection do
        delete 'destroy_multiple'
      end

      resource :highlight, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :reports, only: [:index, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get '/customers', to: 'users#index'
    delete '/customers/delete/:id', to: 'users#destroy', as: 'delete_customer'
    get '/profile/edit', to: 'admins#edit'
    patch '/profile/edit', to: 'admins#update'
    post '/send_testimonial_link/:id', to: 'users#send_testimonial_link'
    get '/password/edit', to: 'passwords#edit'
    patch '/password/edit', to: 'passwords#update'
    get '/search', to: 'searches#index'
  end

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/privacy-policy', to: 'pages#privacy_policy'
  get '/contact', to: 'users/emails#new'
  post '/contact', to: 'users/emails#create'
  get '/testimonials', to: 'users/testimonials#index'
  get '/testimonial/:token', to: 'users/testimonials#new', as: 'new_user_testimonial'
  post '/testimonial/:token', to: 'users/testimonials#create'
  get '/photos', to: 'users/photos#index'
  get 'expired_token', to: 'users/testimonials#expired_token', as: 'expired_token'
  get 'api/density_altitude', to: 'api/density_altitude#create'
end

app/views/admin/admins/edit.html.erb
<% content_for :title, 'Account' %>
<%= render partial: 'shared/nav', locals: { active: 'accounts' } %>
<main>
  <section class="partial-38 shadow border rounded p-3">
    <h1 class="h3 text-primary text-center">Edit Your Profile</h1>
    <% if @user.errors.present? %>
      <section class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
        <%= button_tag(type: 'button', class: 'close', data: {dismiss: 'alert'}, aria: {label: 'Close'}) do %>
          <%= content_tag :span, aria: {hidden: 'true'} do %>
            &times;
          <% end %>
        <% end %>
        <% error_count = @user.errors.count %>
        <h4 class="lead bold">
          The following <%= pluralize(error_count, 'error') %>
          prevented your account from being updated:
        </h4>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </section>
    <% end %>
    <%= form_with model: @user, url: admin_profile_edit_path, local: true, method: :patch do |f| %>
      <dl>
        <dt class="mb-2">Full Name</dt>
        <dd><%= f.text_field :full_name, class: "form-control" %></dd>
      </dl>
      <dl>
        <dt class="mb-2">Phone Number</dt>
        <dd><%= f.text_field :phone_number, class: "form-control" %></dd>
      </dl>
      <dl>
        <dt class="mb-2">Email Address</dt>
        <dd><%= f.text_field :email, class: "form-control" %></dd>
      </dl>
      <dl>
        <dt class="mb-2">Last Sign In</dt>
        <dd>
          <%= format_datetime(@user.last_sign_in_at) %>
        </dd>
      </dl>
      <hr class="my-4">
      <div>
        <%= f.submit 'Update', class: "btn btn-outline-secondary btn-block mb-2" %>
        <%= link_to 'Change Password?', admin_password_edit_path, class: 'd-block text-secondary' %>
        <%= link_to 'Cancel?', admin_root_path, class: 'd-block text-secondary' %>
      </div>
    <% end %>
  </section>
</main>

app/views/admin/admins/index.html.erb
<% content_for :title, 'Dashboard' %>
<%= render partial: 'shared/nav', locals: { active: 'dashboard'} %>
<%= render partial: 'admin/shared/small_nav' %>
<div class="container-fluid">
  <div class="row">
    <%= render partial: 'admin/shared/side_nav' %>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <header class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard
          <span class="lead">/ Home</span>
        </h1>
      </header>
      <section class="jumbotron">
        <section>
          <h2 class="h4">Emails</h2>
          <p class="lead">You have <%= Email.count %> stored <%= 'email'.pluralize(Email.count) %>!</p>
          <%= link_to 'Stored Emails', admin_emails_path %>
        </section>
        <hr class="my-4">
        <section>
          <h2 class="h4">Testimonials</h2>
          <% testimonial_count = Testimonial.where(:published => false).count %>
          <p class="lead">You have  <%= testimonial_count %> stored <%= 'testimonial'.pluralize(testimonial_count) %> waiting for approval!</p>
          <%= link_to 'Testimonials Awaiting Approval',  admin_testimonials_path(:published => false) %>
        </section>
      </section>
    </main>
  </div>
</div>