config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '/user', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  namespace :users, path: '/user' do
    get '/testimonial', to: 'testimonials#edit'
    patch '/testimonial', to: 'testimonials#update'
    delete '/testimonial', to: 'testimonials#destroy'
  end

  namespace :admin do
    root 'admins#index'

    resources :emails, only: [:index, :show, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :testimonials do
      collection do
        delete 'destroy_multiple'
      end

      resource :highlight, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :reports, only: [:index, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get '/customers', to: 'users#index'
    delete '/customers/delete/:id', to: 'users#destroy', as: 'delete_customer'
    get '/profile/edit', to: 'admins#edit'
    patch '/profile/edit', to: 'admins#update'
    post '/send_testimonial_link/:id', to: 'users#send_testimonial_link'
    get '/password/edit', to: 'passwords#edit'
    patch '/password/edit', to: 'passwords#update'
    get '/search', to: 'searches#index'
  end

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/privacy-policy', to: 'pages#privacy_policy'
  get '/contact', to: 'users/emails#new'
  post '/contact', to: 'users/emails#create'
  get '/testimonials', to: 'users/testimonials#index'
  get '/testimonial/:token', to: 'users/testimonials#new', as: 'new_user_testimonial'
  post '/testimonial/:token', to: 'users/testimonials#create'
  get '/photos', to: 'users/photos#index'
  get 'expired_token', to: 'users/testimonials#expired_token', as: 'expired_token'
  get 'api/density_altitude', to: 'api/density_altitude#create'
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  include Paginationable

  has_one :highlight
  has_rich_text :message

  validates_presence_of :message
  validates_presence_of :creator
  validates_presence_of :creator_email
  validates_presence_of :creator_avatar_url

  private

  def self.query_by_term(search_term)
    if search_term.present?
      search_term.downcase!
      Testimonial.where("lower(creator_email) LIKE ? OR lower(creator) LIKE ?",
                        "%#{search_term}%", "%#{search_term}%")
                 .to_a
    else
      []
    end
  end
end

app/models/user.rb
require 'digest/md5'

class User < ApplicationRecord
  include Tokenable
  include Paginationable
  include Searchable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :timeoutable, :omniauthable, :confirmable

  validates_presence_of :full_name

  before_save :create_avatar_url

  protected

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  private

  def self.authenticate(email, password)
    user = self.find_for_authentication(:email => email)
    user && user.valid_password?(password) ? user : nil
  end

  def create_avatar_url
    email_address = self.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    self.avatar_url = "#{hash}?d=mm"
  end
end

app/controllers/admin/testimonials_controller.rb
class Admin::TestimonialsController < Admin::BaseController
  before_action :set_filter!, only: :index
  before_action :set_records_count!, only: :index
  before_action :set_pagination_values!, only: :index

  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = create_testimonial
    if @testimonial.valid?
      if params[:testimonial][:highlight].present?
        @highlight = create_highlight
        if @highlight.valid?
          flash[:success] = 'Your testimonial has been created!'
          redirect_to admin_testimonials_path
        else
          flash[:error] = 'A problem was encountered while submitting your hightlight'
          redirect_to new_admin_testimonial_highlight_path(@testimonial)
        end
      else
        flash[:success] = 'Your testimonial has been saved!'
        redirect_to admin_testimonials_path
      end
    else
      flash.now[:error] = 'Your testimonial could not be submitted'
      render :new
    end
  end

  def index
    @testimonials = Testimonial.limit_and_sort(10 * (@current_page - 1), { :created_at => @order }, build_filter)
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def update
    @testimonial = Testimonial.find(params[:id])
    @testimonial.update(
      :message => params[:testimonial][:message],
      :published => params[:testimonial][:published]
    )
    if @testimonial.valid?
      flash[:success] = 'The testimonial has been updated'
      redirect_to admin_testimonials_path
    else
      flash.now[:error] = 'The testimonial could not be updated'
      render :edit
    end
  end

  def destroy
    Testimonial.find(params[:id]).delete
    flash[:success] = 'The selected testimoial has been deleted'
    redirect_to admin_testimonials_path
  end

  def destroy_multiple
    testimonial_ids = params[:testimonials].keys.map(&:to_i)
    Testimonial.where(id: testimonial_ids).delete_all
    flash[:success] = 'The selected testimonials have been deleted'
    redirect_to admin_testimonials_path
  end

  private

  def create_testimonial
    Testimonial.create(
      :creator => params[:testimonial][:creator],
      :creator_email => params[:testimonial][:creator_email],
      :creator_avatar_url => create_avatar_url(params[:testimonial][:creator_email]),
      :message => params[:testimonial][:message],
      :published => params[:testimonial][:published]
    )
  end

  def create_highlight
    Highlight.create(
      :testimonial_id => @testimonial.id,
      :highlight => params[:testimonial][:highlight]
    )
  end

  def create_avatar_url(email)
    return unless email
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "#{hash}?d=mm"
  end

  def set_records_count!
    if @filter
      @records_count = Testimonial.where(:published => @filter).count
    else
      @records_count = Testimonial.count
    end
  end

  def set_filter!
    if %w(true false).include?(params[:published])
      @filter = params[:published]
    else
      @filter = nil
    end
  end

  def build_filter
    query = nil
    if %w(true false).include?(@filter)
      query = { :published => @filter }
    end
    query
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_records_count!, only: :index
  before_action :set_pagination_values!, only: :index

  def index
    @customers = User.limit_and_sort(10 * (@current_page - 1), { :full_name => @order }, { :admin => false })
  end

  def destroy
    User.destroy(params[:id])
    flash[:success] = 'The account has been successfully removed'
    redirect_to admin_customers_path
  end

  def send_testimonial_link
    SendTestimonialLinkEmailJob.perform_later(params[:id])
    flash[:success] = 'A link for the testimonial has been sent'
    redirect_to admin_customers_path
  end

  private

  def set_records_count!
    @records_count = User.where.not(admin: true).count
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  prepend_before_action :check_captcha, only: [:create]
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end

  private

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new
      respond_with_navigational(resource) { render :new }
    end
  end
end

app/controllers/users/emails_controller.rb
class Users::EmailsController < ApplicationController
  def new
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if verify_recaptcha && @email.save
      SendContactEmailJob.perform_later('user', @email.id)
      SendContactEmailJob.perform_later('admin', @email.id)
      flash[:success] = 'Your email has been sent'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def email_params
    params.require(:email).permit(:full_name, :email, :phone_number, :message)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  prepend_before_action :check_captcha, only: [:create]
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  private

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new
      respond_with_navigational(resource) { render :new }
    end
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  def index
    @images = Dir.glob('app/assets/images/photos/*.jpg')
    @images.map! { |img| img.split('/').last }
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  prepend_before_action :check_captcha, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    @testimonial = Testimonial.find_by(:creator_email => resource.email)
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
    def check_captcha
      unless verify_recaptcha
        self.resource = resource_class.new sign_up_params
        resource.validate # Look for any other validation errors besides Recaptcha
        set_minimum_password_length
        respond_with_navigational(resource) { render :new }
      end
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  prepend_before_action :check_captcha, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  private

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new sign_in_params
      respond_with_navigational(resource) { render :new }
    end
  end
end

app/controllers/users/testimonials_controller.rb
class Users::TestimonialsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_records_count!, only: :index
  before_action :set_pagination_values!, only: :index

  def index
    @testimonials = Testimonial.limit_and_sort(10 * (@current_page - 1), { :created_at => 'desc' })
  end

  def new
    @user = User.find_by(testimonial_token: params[:token])
    if @user
      @testimonial = Testimonial.new
    else
      flash[:error] = 'An error was encountered while processing your request!'
       redirect_to expired_token_path
    end
  end

  def create
    @user = User.find_by(testimonial_token: params[:token])
    if @user
      @testimonial = Testimonial.new(testimonial_params.merge(
        {
          creator: params[:creator],
          creator_email: params[:creator_email],
          creator_avatar_url: params[:creator_avatar_url]
        }
      ))

      if verify_recaptcha && @user && @testimonial.save
        @user.update(:testimonial_token => User.generate_token)
        SendThankYouEmailJob.perform_later('user', @user.id)
        SendThankYouEmailJob.perform_later('admin', @user.id)
        flash[:success] = 'Your testimonial has been added!'
        redirect_to root_path
      else
        flash[:error] = 'Your testimonial could not be submitted!'
        render 'new'
      end
    else
      flash[:error] = 'An error was encountered while processing your request!'
      redirect_to expired_token_path
    end
  end

  def edit
    @user = current_user
    @testimonial = Testimonial.find_by(:creator_email => @user.email)
  end

  def update
    @testimonial = Testimonial.find_by(:creator_email => current_user.email)
    @testimonial.update(:message => params[:testimonial][:message])
    if @testimonial.valid?
      flash[:success] = 'Your testimonail has been updated'
      redirect_to edit_user_registration_path
    else
      flash.now[:error] = 'Your testimonial could not be updated'
      render :edit
    end
  end

  def destroy
    Testimonial.find_by(:creator_email => current_user.email).delete
    flash[:success] = 'Your testimonial has been deleted'
    redirect_to edit_user_registration_path
  end

  def expired_token; end

  private

  def testimonial_params
    params.require(:testimonial).permit(:message)
  end

  def set_records_count!
    @records_count = Testimonial.where(:published => true).count
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/testimonials/edit.html.erb
<% content_for :title, 'Edit Testimonial' %>
<%= javascript_pack_tag 'application' %>
<%= render partial: 'shared/nav', locals: { active: 'accounts' } %>
<main class="partial-60 my-5">
  <%= render partial: 'devise/shared/sub_nav', locals: { active: 'testimonial' } %>
  <section class="border border-top-0 rounded-bottom shadow px-4">
    <h1 class="py-3 text-primary text-center">My Testimonial</h2>
    <%= form_with model: @testimonial, url: users_testimonial_path, method: :patch, local: true do |f| %>
      <% if @testimonial.errors.present? %>
        <section class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
          <%= button_tag(type: 'button', class: 'close', data: {dismiss: 'alert'}, aria: {label: 'Close'}) do %>
            <%= content_tag :span, aria: {hidden: 'true'} do %>
              &times;
            <% end %>
          <% end %>
          <% error_count = @testimonial.errors.count %>
          <h4 class="lead bold">
            The following <%= pluralize(error_count, 'error') %>
            prevented your testimonial from being updated:
          </h4>
          <ul>
            <% @testimonial.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </section>
      <% end %>
      <%= f.rich_text_area :message, class: ('field_with_errors' if @testimonial.errors.keys.include?(:message)) %>
      <div class="form-actions mt-5">
        <%= f.submit 'Update', class: "mb-2 btn btn-outline-secondary" %>
        <button type="button" class="mb-2 btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">
          Delete
        </button>

        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="modal-title-account-delete">Are you sure you want to delete your testimonial?</h5>
                <button type="button" class="close text-right" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                This action can't be undone
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                <%= link_to 'Delete', users_testimonial_path, method: :delete, class: 'btn btn-outline-danger' %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= link_to "Cancel", :back, class: 'd-block mb-3' %>
    <% end %>
  </section>
</main>

app/views/users/testimonials/expired_token.html.haml
= content_for :title, 'Expired Token' 
= render partial: 'shared/nav', locals: { active: '' }
%main
  %section.partial-60.shadow.rounded.my-5.p-4
    %h1.token_error.text-center.pt-0
      Token Error
    %p.token_error.text-center
      That token has expired or has been used. If you believe you have reached this
      page in error please
      =link_to 'contact us!', contact_path

app/views/users/testimonials/index.html.erb
<% content_for :title, 'Testimonials' %>
<%= render partial: 'shared/nav', locals: { active: 'testimonials' } %>
<main class="container">
  <header class="testimonial-header text-center mt-4">
    <h1 class="text-primary pb-0 mb-0">TESTIMONIALS</h1>
    <hr class="break">
    <p class="lead">See what people are saying about us!</p>
  </header>
  <section id="testimonials" class="card-columns mt-5">
    <% @testimonials.each do |testimonial| %>
      <section class="card shadow border rounded p-4 my-3 text-center">
        <%= image_tag("https://www.gravatar.com/avatar/#{testimonial.creator_avatar_url}&s=80", class: 'avatar mx-auto') %>
        <p class="text-center mt-1 mb-3"><strong><em><%= testimonial.creator.titleize %></em></strong></p>
        <%= fa_icon 'quote-right', class: 'testimonial-quote'%>
        <%= testimonial.message %>
      </section>
    <% end %>
  </section>
  <nav aria-label="page navigation">
    <ul class="pagination justify-content-center">
      <% if @current_page == 1 %>
        <li class="page-item disabled">
          <%= link_to testimonials_path(:page => @current_page - 1), class: "page-link", aria: {label: "Previous"} do %>
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          <% end %>
        </li>
      <% else %>
        <li class="page-item">
          <%= link_to testimonials_path(:page => @current_page - 1), class: "page-link", aria: {label: "Previous"} do %>
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          <% end %>
        </li>
      <% end %>
      <% (@records_count / 10.0).ceil.times do |n| %>
        <% if @current_page == n + 1 %>
          <li class="page-item active" %>
            <%= link_to n + 1, testimonials_path(:page => n + 1), class: "page-link" %>
        <% else %>
          <li class="page-item" %>
            <%= link_to n + 1, testimonials_path(:page => n + 1), class: "page-link" %>
          </li>
        <% end %>
      <% end %>
      <% if @current_page < (@records_count / 10.0).ceil %>
        <li class="page-item">
          <%= link_to testimonials_path(:page => @current_page + 1), class: "page-link", aria: {label: "Next"} do %>
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          <% end %>
        </li>
      <% else %>
        <li class="page-item disabled">
          <%= link_to testimonials_path(:page => @current_page + 1), class: "page-link", aria: {label: "Next"} do %>
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
  <div class="backdrop">
    <%= link_to nil, id: "modal-close"  do %>
      <%= fa_icon 'times'%>
    <% end %>
  </div>
  <figure id="lightbox-image" class="full-size-image">
    <img src="">
    <figcaption class="attachment__caption">
    </figcaption>
  </figure>
</main>

<%= javascript_pack_tag 'lightbox' %>

app/views/users/testimonials/new.html.haml
= content_for :title, 'New Testimonial'
= javascript_pack_tag 'application'
= render partial: 'shared/nav', locals: { active: '' }
%main
  %section.bg-light.partial-60.shadow.rounded.px-4.my-4
    %div.row
      %div.col-sm-12.mt-4
        %h1.mb-1.text-primary LEAVE A TESTIMONIAL
        %p.lead
          We appreciate your feedback
          %span.bold #{@user.full_name.titleize}
          !
    - if @testimonial.errors.present?
      %div.alert.alert-danger.alert-dismissible.fade.show{role: 'alert'}
        = button_tag(type: 'button', class: 'close', data: {dismiss: 'alert'}, aria: {label: 'Close'}) do
          = content_tag :span, aria: {hidden: 'true'} do
            &times;
        - error_count = @testimonial.errors.count
        %h4.lead.bold The following #{pluralize(error_count, 'error')} prevented your Testimonial from being saved:
        %ul
          - @testimonial.errors.full_messages.each do |msg|
            %li= msg
    %div.row.mt-3
      = form_with url: new_user_testimonial_path, method: 'post', scope: 'testimonial', local: true, class: 'col' do |f|
        %div.form-row.mb-3.mt-3
          = hidden_field_tag :token, @user.testimonial_token
          = hidden_field_tag :creator_avatar_url, @user.avatar_url
          = hidden_field_tag :creator, @user.full_name
          = hidden_field_tag :creator_email, @user.email
          %div.col
            = f.rich_text_area :message, placeholder: 'Message and Images', id: 'testimonial_message', class: ('field_with_errors' if @testimonial.errors[:message].present?)
        %hr
        %div.form-row.mt-3.mb-5
          = invisible_recaptcha_tags ui: :input, text: 'Submit', class: 'col-sm-2 btn btn-primary'