config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '/user', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  namespace :users, path: '/user' do
    get '/testimonial', to: 'testimonials#edit'
    patch '/testimonial', to: 'testimonials#update'
    delete '/testimonial', to: 'testimonials#destroy'
  end

  namespace :admin do
    root 'admins#index'

    resources :emails, only: [:index, :show, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    resources :testimonials do
      collection do
        delete 'destroy_multiple'
      end

      resource :highlight, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :reports, only: [:index, :delete, :destroy] do
      collection do
        delete 'destroy_multiple'
      end
    end

    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get '/customers', to: 'users#index'
    delete '/customers/delete/:id', to: 'users#destroy', as: 'delete_customer'
    get '/profile/edit', to: 'admins#edit'
    patch '/profile/edit', to: 'admins#update'
    post '/send_testimonial_link/:id', to: 'users#send_testimonial_link'
    get '/password/edit', to: 'passwords#edit'
    patch '/password/edit', to: 'passwords#update'
    get '/search', to: 'searches#index'
  end

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/privacy-policy', to: 'pages#privacy_policy'
  get '/contact', to: 'users/emails#new'
  post '/contact', to: 'users/emails#create'
  get '/testimonials', to: 'users/testimonials#index'
  get '/testimonial/:token', to: 'users/testimonials#new', as: 'new_user_testimonial'
  post '/testimonial/:token', to: 'users/testimonials#create'
  get '/photos', to: 'users/photos#index'
  get 'expired_token', to: 'users/testimonials#expired_token', as: 'expired_token'
  get 'api/density_altitude', to: 'api/density_altitude#create'
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  include Paginationable

  has_one :highlight
  has_rich_text :message

  validates_presence_of :message
  validates_presence_of :creator
  validates_presence_of :creator_email
  validates_presence_of :creator_avatar_url

  private

  def self.query_by_term(search_term)
    if search_term.present?
      search_term.downcase!
      Testimonial.where("lower(creator_email) LIKE ? OR lower(creator) LIKE ?",
                        "%#{search_term}%", "%#{search_term}%")
                 .to_a
    else
      []
    end
  end
end

app/controllers/admin/testimonials_controller.rb
class Admin::TestimonialsController < Admin::BaseController
  before_action :set_filter!, only: :index
  before_action :set_records_count!, only: :index
  before_action :set_pagination_values!, only: :index

  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = create_testimonial
    if @testimonial.valid?
      if params[:testimonial][:highlight].present?
        @highlight = create_highlight
        if @highlight.valid?
          flash[:success] = 'Your testimonial has been created!'
          redirect_to admin_testimonials_path
        else
          flash[:error] = 'A problem was encountered while submitting your hightlight'
          redirect_to new_admin_testimonial_highlight_path(@testimonial)
        end
      else
        flash[:success] = 'Your testimonial has been saved!'
        redirect_to admin_testimonials_path
      end
    else
      flash.now[:error] = 'Your testimonial could not be submitted'
      render :new
    end
  end

  def index
    @testimonials = Testimonial.limit_and_sort(10 * (@current_page - 1), { :created_at => @order }, build_filter)
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def update
    @testimonial = Testimonial.find(params[:id])
    @testimonial.update(
      :message => params[:testimonial][:message],
      :published => params[:testimonial][:published]
    )
    if @testimonial.valid?
      flash[:success] = 'The testimonial has been updated'
      redirect_to admin_testimonials_path
    else
      flash.now[:error] = 'The testimonial could not be updated'
      render :edit
    end
  end

  def destroy
    Testimonial.find(params[:id]).delete
    flash[:success] = 'The selected testimoial has been deleted'
    redirect_to admin_testimonials_path
  end

  def destroy_multiple
    testimonial_ids = params[:testimonials].keys.map(&:to_i)
    Testimonial.where(id: testimonial_ids).delete_all
    flash[:success] = 'The selected testimonials have been deleted'
    redirect_to admin_testimonials_path
  end

  private

  def create_testimonial
    Testimonial.create(
      :creator => params[:testimonial][:creator],
      :creator_email => params[:testimonial][:creator_email],
      :creator_avatar_url => create_avatar_url(params[:testimonial][:creator_email]),
      :message => params[:testimonial][:message],
      :published => params[:testimonial][:published]
    )
  end

  def create_highlight
    Highlight.create(
      :testimonial_id => @testimonial.id,
      :highlight => params[:testimonial][:highlight]
    )
  end

  def create_avatar_url(email)
    return unless email
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "#{hash}?d=mm"
  end

  def set_records_count!
    if @filter
      @records_count = Testimonial.where(:published => @filter).count
    else
      @records_count = Testimonial.count
    end
  end

  def set_filter!
    if %w(true false).include?(params[:published])
      @filter = params[:published]
    else
      @filter = nil
    end
  end

  def build_filter
    query = nil
    if %w(true false).include?(@filter)
      query = { :published => @filter }
    end
    query
  end
end

app/controllers/users/testimonials_controller.rb
class Users::TestimonialsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_records_count!, only: :index
  before_action :set_pagination_values!, only: :index

  def index
    @testimonials = Testimonial.limit_and_sort(10 * (@current_page - 1), { :created_at => 'desc' })
  end

  def new
    @user = User.find_by(testimonial_token: params[:token])
    if @user
      @testimonial = Testimonial.new
    else
      flash[:error] = 'An error was encountered while processing your request!'
       redirect_to expired_token_path
    end
  end

  def create
    @user = User.find_by(testimonial_token: params[:token])
    if @user
      @testimonial = Testimonial.new(testimonial_params.merge(
        {
          creator: params[:creator],
          creator_email: params[:creator_email],
          creator_avatar_url: params[:creator_avatar_url]
        }
      ))

      if verify_recaptcha && @user && @testimonial.save
        @user.update(:testimonial_token => User.generate_token)
        SendThankYouEmailJob.perform_later('user', @user.id)
        SendThankYouEmailJob.perform_later('admin', @user.id)
        flash[:success] = 'Your testimonial has been added!'
        redirect_to root_path
      else
        flash[:error] = 'Your testimonial could not be submitted!'
        render 'new'
      end
    else
      flash[:error] = 'An error was encountered while processing your request!'
      redirect_to expired_token_path
    end
  end

  def edit
    @user = current_user
    @testimonial = Testimonial.find_by(:creator_email => @user.email)
  end

  def update
    @testimonial = Testimonial.find_by(:creator_email => current_user.email)
    @testimonial.update(:message => params[:testimonial][:message])
    if @testimonial.valid?
      flash[:success] = 'Your testimonail has been updated'
      redirect_to edit_user_registration_path
    else
      flash.now[:error] = 'Your testimonial could not be updated'
      render :edit
    end
  end

  def destroy
    Testimonial.find_by(:creator_email => current_user.email).delete
    flash[:success] = 'Your testimonial has been deleted'
    redirect_to edit_user_registration_path
  end

  def expired_token; end

  private

  def testimonial_params
    params.require(:testimonial).permit(:message)
  end

  def set_records_count!
    @records_count = Testimonial.where(:published => true).count
  end
end

app/views/testimonials/edit.html.erb
<%= javascript_pack_tag 'application' %>
<%= render partial: 'shared/nav', locals: { active: 'dashboard'} %>
<div class="container-fluid">
  <div class="row">
    <%= render partial: 'admins/shared/side_nav' %>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <header class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">
          Dashboard
          <span class="lead">/ Testimonials / Edit</span>
        </h1>
      </header>
      <section class="bg-light p-3 mb-3">
        <%= form_with model: @testimonial, url: admin_testimonial_path(current_user, @testimonial), method: :patch, local: true do |f| %>
          <% if @testimonial.errors.present? %>
            <section class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
              <%= button_tag(type: 'button', class: 'close', data: {dismiss: 'alert'}, aria: {label: 'Close'}) do %>
                <%= content_tag :span, aria: {hidden: 'true'} do %>
                  &times;
                <% end %>
              <% end %>
              <% error_count = @testimonial.errors.count %>
              <h4 class="lead bold">
                The following <%= pluralize(error_count, 'error') %>
                prevented your email from being sent:
              </h4>
              <ul>
                <% @testimonial.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </section>
          <% end %>
          <section class="row">
            <dl class="col-sm">
              <dt>Full Name:</dt>
              <dd><%= @testimonial.creator.full_name.titleize %></dd>
            </dl>
            <dl class="col-sm">
              <dt>Email Address:</dt>
              <dd><%= @testimonial.creator.email %></dd>
            </dl>
            <dl class="col-sm">
              <dt>Submitted:</dt>
              <dd><%= format_datetime(@testimonial.created_at) %></dd>
            </dl>
            <dl class="col-sm">
              <dt>Published:</dt>
              <% if @testimonial.published == true %>
                <dd class="text-success"><%= @testimonial.published %></dd>
              <% else %>
                <dd class="text-danger"><%= @testimonial.published %></dd>
              <% end %>
            </dl>
            <dl class="col-sm-12">
              <dt>
                <%= label_tag 'testimonial[created_by]' do %>
                  Created By:
                  <span>(publically viewed)</span>
                <% end %>
              </dt>
              <dd>
                <%= f.text_field :created_by, class: 'bg-light'%>
              </dd>
            </dl>
            <dl class="col-sm-12">
              <dt>
                <%= f.label 'testimonial[published]', 'Publish?' %>
              </dt>
              <dd>
                <%= f.select :published, options_for_select([['Yes', true], ['No', false]], @testimonial.published) %>
              </dd>
            </dl>
          </section>
          <hr class="my-2">
          <section class="row">
            <dl class="col-sm">
              <dt>Testimonial:</dt>
              <dd>
                <%= f.rich_text_area :message, class: ('field_with_errors' if @testimonial.errors.keys.include?(:message)) %>
              </dd>
            </dl>
          </section>
          <p>
            <% if @testimonial.highlight %>
              <%= link_to 'Edit highlight',  edit_admin_testimonial_highlight_path(current_user, @testimonial), class: 'btn btn-outline-secondary' %>
            <% else %>
              <%= link_to 'Add a highlight',   new_admin_testimonial_highlight_path(current_user, @testimonial), class: 'btn btn-outline-secondary' %>
            <% end %>
          </p>
          <hr class="my-4">
          <section class="row form-actions">
            <%= f.submit 'Update', class: 'btn btn-outline-secondary col-lg-2' %>
            <%= link_to 'Delete', admin_testimonial_path(current_user, @testimonial), method: :delete, class: 'btn btn-outline-danger col-lg-2' %>
          </section>
        <% end %>
      </section>
    </main>
  </div>
</div>

app/views/testimonials/index.html.erb
<%= render partial: 'shared/nav', locals: { active: 'dashboard'} %>
<div class="container-fluid">
  <div class="row">
    <%= render partial: 'admins/shared/side_nav' %>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <header class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">
          Dashboard
          <span class="lead">/ Testimonials</span>
        </h1>
        <% if @order == 'desc' %>
          <%= link_to admin_testimonials_path(current_user, build_query_params(:page => @current_page, :order => 'asc', :published => @filter)), class: 'btn btn-sm btn-outline-secondary'  do %>
            <%= fa_icon 'caret-up', class: 'pr-1' %>
            Sort By Ascending
          <% end %>
        <% else %>
          <%= link_to admin_testimonials_path(current_user, build_query_params(:page => @current_page, :order => 'desc', :published => @filter)), class: 'btn btn-sm btn-outline-secondary'  do %>
            <%= fa_icon 'caret-down', class: 'pr-1' %>
            Sort By Descending
          <% end %>
        <% end %>
      </header>
      <section class="bg-light p-3 mb-3">
        <ul class="nav nav-tabs mb-4">
          <li class="nav-item">
            <% if @filter == nil %>
              <%= link_to 'All', admin_testimonials_path(current_user), class: 'nav-link active' %>
            <% else %>
              <%= link_to 'All', admin_testimonials_path(current_user), class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item">
            <% if @filter == 'true' %>
              <%= link_to 'Published', admin_testimonials_path(current_user, build_query_params(:published => :true)), class: 'nav-link active' %>
            <% else %>
              <%= link_to 'Published', admin_testimonials_path(current_user, build_query_params(:published => :true)), class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item">
            <% if @filter == 'false' %>
              <%= link_to 'Unpublished', admin_testimonials_path(current_user, :published => :false), class: 'nav-link active' %>
            <% else %>
              <%= link_to 'Unpublished', admin_testimonials_path(current_user, :published => :false), class: 'nav-link' %>
            <% end %>
          </li>
        </ul>
        <% if @records_count == 0 %>
          <h2 class="h3">You don't have any testimonials to show!</h2>
        <% else %>
          <%= form_for :testimonials, url: destroy_multiple_admin_testimonials_path(current_user, @testimonial, :page => @current_page, :order => @order), method: :delete do |f| %>
            <% @testimonials.each_with_index do |testimonial, idx| %>
              <dl class="row">
                <dt class="col-lg-auto">Email:</dt>
                <dd class="col-lg-auto"><%= testimonial.creator.email %></dd>
                <dt class="col-lg-auto">Name:</dt>
                <dd class="col-lg-auto"><%= testimonial.creator.full_name %></dd>
                <dt class="col-lg-auto">Sent:</dt>
                <dd class="col-lg-auto"><%= format_datetime(testimonial.created_at) %></dd>
              </dl>
              <dl class="row">
                <dt class="col-lg-auto">Published:</dt>
                <% if testimonial.published == true %>
                  <dd class="col-lg-auto text-success">True</dd>
                <% else %>
                  <dd class="col-lg-auto text-danger">False</dd>
                <% end %>
              </dl>
              <% if testimonial.highlight != nil %>
                <dl class="row">
                  <dt class="col-lg-auto">Highlight:</dt>
                  <dd class="col-lg-auto">Attached</dd>
                </dl>
              <% end %>
              <div class="row">
                <div class="col-sm-12">
                  <%= check_box_tag "testimonials[#{testimonial.id}]", true %>
                  <%= link_to 'Edit', edit_admin_testimonial_path(current_user, testimonial), class: "btn btn-sm btn-outline-secondary ml-2" %>
                  <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#testimonial-<%= testimonial.id %>">
                    Delete
                  </button>
                  <div class="modal fade" id="testimonial-<%= testimonial.id %>" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="modal-title-<%= testimonial.id %>">Are you sure you want to delete this testimonial?</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          This action can't be undone
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                          <%= link_to 'Delete', admin_testimonial_path(current_user, testimonial, :page => @current_page, :order => @order), method: :delete, class: 'btn btn-outline-danger' %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="my-4">
            <% end %>
            <%= f.submit 'Delete Selected', class: "btn btn-outline-danger" %>
          <% end %>
        <% end %>
      </section>
      <% unless @records_count == 0 %>
        <%= render partial: 'testimonials_pagination' %>
      <% end %>
    </main>
  </div>
</div>

app/views/testimonials/show.html.erb
<%= javascript_pack_tag 'application' %>
<%= render partial: 'shared/nav', locals: { active: 'dashboard'} %>
<div class="container-fluid">
  <div class="row">
    <%= render partial: 'admins/shared/side_nav' %>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <header class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">
          Dashboard
          <span class="lead">/ Testimonials / Show</span>
        </h1>
      </header>
      <section class="bg-light p-3 mb-3">
        <%= form_for @testimonial, url: admin_testimonial_path(current_user, @testimonial), method: :patch do |f| %>
          <% if @testimonial.errors.present? %>
            <section class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
              <%= button_tag(type: 'button', class: 'close', data: {dismiss: 'alert'}, aria: {label: 'Close'}) do %>
                <%= content_tag :span, aria: {hidden: 'true'} do %>
                  &times;
                <% end %>
              <% end %>
              <% error_count = @testimonial.errors.count %>
              <h4 class="lead bold">
                The following <%= pluralize(error_count, 'error') %>
                prevented your email from being sent:
              </h4>
              <ul>
                <% @testimonial.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </section>
          <% end %>
          <section class="row">
            <dl class="col-sm">
              <dt>Full Name:</dt>
              <dd><%= @testimonial.user.full_name.titleize %></dd>
            </dl>
            <dl class="col-sm">
              <dt>Email Address:</dt>
              <dd><%= @testimonial.user.email %></dd>
            </dl>
            <dl class="col-sm">
              <dt>Submitted:</dt>
              <dd><%= format_datetime(@testimonial.created_at) %></dd>
            </dl>
            <dl class="col-sm">
              <dt>Published:</dt>
              <% if @testimonial.published == true %>
                <dd class="text-success"><%= @testimonial.published %></dd>
              <% else %>
                <dd class="text-danger"><%= @testimonial.published %></dd>
              <% end %>
            </dl>
            <dl class="col-sm-12">
              <dt>
                <%= label_tag 'testimonial[created_by]' do %>
                  Created By:
                  <span>(publically viewed)</span>
                <% end %>
              </dt>
              <dd>
                <%= f.text_field :created_by, value: format_name(@testimonial.user.full_name), class: 'bg-light'%>
              </dd>
            </dl>
            <dl class="col-sm-12">
              <dt>
                <%= label_tag 'testimonial[published]', 'Publish?' %>
              </dt>
              <dd>
                <%= f.select :published, options_for_select([['Yes', true], ['No', false]], @testimonial.published) %>
              </dd>
            </dl>
          </section>
          <hr class="my-2">
          <section class="row">
            <dl class="col-sm">
              <dt>Message:</dt>
              <dd class="px-5 pt-5"><%= @testimonial.message %></dd>
            </dl>
          </section>
          <hr class="my-4">
          <section class="row">
            <dl class="col-sm-12">
              <dt class="mb-3">
                <%= label_tag 'testimonial[testimonial_highlight]' do %>
                  Highlight:
                  <span>(Truncated Version)</span>
                <% end %>
              </dt>
              <dd>
                <%= f.rich_text_area :highlight, value: @testimonial.highlight, class: ('field_with_errors' if @testimonial.errors.keys.include?(:highlight)) %>
              </dd>
            </dl>
            <p id="characters_remaining" class="text-success"></p>
          </section>
          <hr class="my-4">
          <section class="row">
            <%= f.submit 'Update', class: 'btn btn-outline-secondary col-lg-2' %>
            <%= link_to 'Delete', admin_testimonial_path(current_user, @testimonial), method: :delete, class: 'btn btn-outline-danger col-lg-2' %>
          </section>
        <% end %>
      </section>
    </main>
  </div>
</div>
<script>
  const $REMAINING = $('#characters_remaining');
  const TOTAL = 150;
  const EDITOR = $('trix-editor').get(0);
  const testimonial = {
    init: function() {
      this.bindEvents();
      this.calculateCount(EDITOR);
    },
    bindEvents: function() {
      $('trix-editor').on('trix-change', this.calculateCount.bind(this));
    },
    calculateCount: function() {
      const { editor } = EDITOR
      const string = editor.getDocument().toString()
      const characterCount = string.length - 1
      this.changeRemainingCount(characterCount)
    },
    changeRemainingCount: function(count) {
      const charsRemaining = TOTAL - count;
      $REMAINING.text('(' + charsRemaining + ' ' + this.pluralize('Character', charsRemaining) + ' Remaining)');
      this.toggleClass(charsRemaining);
    },
    pluralize: function(string, count) {
      if (count === 1 || count === -1) {
        return string;
      } else {
        return string + "s";
      }
    },
    toggleClass: function(charsRemaining) {
      if (charsRemaining >= 0) {
        $REMAINING.toggleClass('text-success', true);
        $REMAINING.toggleClass('text-danger', false);
      } else {
        $REMAINING.toggleClass('text-success', false);
        $REMAINING.toggleClass('text-danger', true);
      }
    }
  };

  testimonial.init();
</script>